name: Publish

on:
  workflow_dispatch:
  push:
    branches:
    - main
jobs:
  publish:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore ./LibraryApi.slnx

    - name: Build
    
      run: dotnet build ./LibraryApi.slnx --configuration Release

    - name: Publish
      run: dotnet publish ./LibraryApi.slnx --configuration Release --no-build
  
  
  
